#ifndef _LANGUAGE_kdfjlskd_H_
#define _LANGUAGE_kdfjlskd_H_

#include <stdint.h>
//#include "lang_xls.h"

typedef enum
{
	LANGUAGE_HANYU = 0,
	LANGUAGE_CHINESE,
	LANGUAGE_ENGLISH,
	LANGUAGE_ELUOSI,
	LANGUAGE_XIBANYA,
	LANGUAGE_YUENAN,
	LANGUAGE_ALABOYU,

    
    LANGUAGE_TOTAL,
} layout_language_t;

typedef enum LANGUAGE_STRING_TYPE_ID
{
    // /*******  home  *******/
    // HOMEDEFAULT_LANG_ID_USE_MOBILE_APP,
    // HOMEDEFAULT_LANG_ID_RECENT_VIDEO, // 启动设置
    // HOMEDEFAULT_LANG_ID_RECENT_CALL,
    // HOMEDEFAULT_LANG_ID_MONITORING,
    // HOMEDEFAULT_LANG_ID_CALL,
    // HOMEDEFAULT_LANG_ID_CCTV,
    // HOMEDEFAULT_LANG_ID_AWAY,
    // HOMEDEFAULT_LANG_ID_BURGLAR,
    // HOMEDEFAULT_LANG_ID_ELEVATOR,
    // HOMEDEFAULT_LANG_ID_EMERGENCY,
    // HOMEDEFAULT_LANG_ID_THE_COMMUNICATION_LINE,
    // HOMEDEFAULT_LANG_ID_DOORCAMERA,
    // HOMEDEFAULT_LANG_ID_COMMON_ENTRANCE,

    /*******  setting  main*******/
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_SETTINGS,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_GENERAL,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_WIFI,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_SOUND,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_SCREEN,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_RECORD_MONITORING,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_INSTALLATION_CONFIGURATION,

    /*******  setting  general*******/
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_AUTO_SETUP,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DATA_AND_TIME,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_LANGUAGE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_PASSWORD,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_CHANNGE_PASSWORD_FOR_SECURITY,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_STORAGE_SPACE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOOR_OPENING_METHOD,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_OPEN_AFTER_CALL,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_OPEN_WHEN_CALL,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOOR_OPENER_MODULE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DIGITAL_DOOR_CAMERA,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DIGITAL_DOOR_LOCK,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOOR_OPEN_NUM,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOOR_OPEN_NUM1,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOOR_OPEN_NUM2,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_CALL_TIMER,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_1_MINUTE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_3_MINUTE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_5_MINUTE,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_DOWNLOAD_MOBILE_APP,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_INITIALIZATION_USER_DATA,
    SETTING_GENERAL_DEFAULT_LANG_ID_LANG_VERSION_INFORMATION,

    LANGUAGE_STRING_TOTAL,
} lang_str_id_t;

char *lang_str_get(lang_str_id_t lang_str_id);

char *lang_str_get_by_language(lang_str_id_t index, layout_language_t language);

int   language_total_get(void);

void write_language_string_to_xls(void);


#endif // _LANGUAGE_H_